<?php

declare(strict_types=1);

namespace Bhitti\Database\Migration\Grammar;

use Bhitti\Database\Migration\ColumnDefinition;

final class PostgresGrammar extends Grammar
{
    protected function quoteCharacter(): string
    {
        return '"';
    }

    protected function columnType(ColumnDefinition $column): string
    {
        $type = match ($column->type()) {
            'string' => 'VARCHAR(' . $column->length() . ')',
            'char' => 'CHAR(' . $column->length() . ')',
            'text', 'mediumText', 'longText' => 'TEXT',
            'tinyInteger', 'smallInteger' => 'SMALLINT',
            'integer' => 'INTEGER',
            'bigInteger' => 'BIGINT',
            'decimal' => 'NUMERIC(' . $column->precision() . ', ' . $column->scale() . ')',
            'float' => 'DOUBLE PRECISION',
            'boolean' => 'BOOLEAN',
            'date' => 'DATE',
            'dateTime', 'timestamp' => 'TIMESTAMP WITHOUT TIME ZONE',
            'json' => 'JSON',
            'uuid' => 'UUID',
            'binary' => 'BYTEA',
        };

        if ($column->isAutoIncrement()) {
            $type .= ' GENERATED BY DEFAULT AS IDENTITY';
        }

        return $type;
    }

    protected function booleanLiteral(bool $value): string
    {
        return $value ? 'TRUE' : 'FALSE';
    }
}
